# Keycloak
docker_build(
  'keycloak',
  '.',
  dockerfile='./keycloak/Dockerfile')

k8s_yaml('./keycloak/keycloak.yml')
k8s_resource('keycloak', labels=['Services'], port_forwards=['9080:9080', '9443:9443', '9990:9990'])

# Postgres
k8s_yaml('./postgres/postgres.yml')
k8s_resource('postgres', labels=['Services'], port_forwards='5432:5432')
