# Build service project
local_resource(
    name = "user-service-build",
    cmd = "mvn clean install -Dquarkus.profile=dev -DskipTests",
    labels = ['Build'],
)

# Docker build
docker_build(
  'heligion-backend-user-service',
  '.',
  dockerfile='./src/main/docker/Dockerfile.jvm')

# Run k8s deployment
k8s_yaml('./target/kubernetes/kubernetes.yml')
k8s_resource('heligion-backend-user-service', labels=['Backend'], resource_deps=['user-service-build'], port_forwards='8080:8080')
